services:
    db:
        image: postgres:latest
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_USER=deno_pim
            - POSTGRES_PASSWORD=deno_pim
            - POSTGRES_DB=deno_pim
